development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %> 

test:
  <<: *default
  #database: compose-postgres-app_test

