data:
  image: postgres
  volumes:
    - /var/lib/postgresql

db:
  image: postgres
  volumes_from: 
    - data
  links:
    - data

web:
  build: .
  ports: 
    - '3333:3000'
  volumes:
    - './:/var/app'
  working_dir: /var/app
  #command: irb
  command: rails s -b '0.0.0.0'
  links:
    - db:db
